[package]
name = "diminuendo"
version = "0.1.0"
authors = ["Kon Rybnikov <k-bx@k-bx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "~0.3.0"
thiserror = "~1.0.24"
